services:
  - type: web
    name: python-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn python_chatbot.wsgi:application
    envVars:
      - key: SERP_API_KEY
        value: your-real-api-key
